name: Generate pacman animation
on:
  schedule:
    # Jalanin tiap jam 12 malem
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  generate:
    # INI KUNCINYA, MAR!
    permissions:
      contents: write 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: platane/platane@v5 # Pake yang ini, udah paling bener
        with:
          # Token buat ngasih izin nulis
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Nama file outputnya
          files: pacman-contribution-graph.svg, pacman-contribution-graph-dark.svg
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          # Anterin semua file ke branch 'output'
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}